[package]
name = "bitgrin_wallet_api"
version = "2.0.0"
authors = ["Bitgrin Developers <bitgrin@protonmail.com>"]
description = "Bitgrin Wallet API"
license = "Apache-2.0"
repository = "https://github.com/bitgrin/bitgrin-wallet"
keywords = [ "crypto", "bitgrin", "mimblewimble" ]
exclude = ["**/*.bitgrin", "**/*.bitgrin2"]
edition = "2018"

[dependencies]
failure = "0.1"
failure_derive = "0.1"
log = "0.4"
uuid = { version = "0.7", features = ["serde", "v4"] }
serde_json = "1"
easy-jsonrpc = "0.5.1"
chrono = { version = "0.4.4", features = ["serde"] }

bitgrin_wallet_libwallet = { path = "../libwallet", version = "2.0.1" }
bitgrin_wallet_config = { path = "../config", version = "2.0.0" }
bitgrin_wallet_impls = { path = "../impls", version = "2.0.0" }
bitgrin_wallet_util = { path = "../util", version = "2.0.0" }

[dev-dependencies]
serde_json = "1"
tempfile = "3.0.7"
